name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 1. Instalar pnpm
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9 # O la versión que uses localmente

    # 2. Instalar dependencias con pnpm
    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      env:
        ORANGE_USERNAME: ${{ secrets.ORANGE_USERNAME }}
        ORANGE_PASSWORD: ${{ secrets.ORANGE_PASSWORD }}
      run: pnpm exec playwright test
